import pandas as pd
import numpy as np

#
start_date=int(2008)
end_date=int(2025)
#Static Infos

np.random.seed(42) # Set random seed for reproducibility

# Define the number of samples
n_samples = 100000

moroccan_cities = [
    "Agadir", "Ahfir", "Ain Harrouda", "Ait Melloul", "Ajdir", "Al Hoceïma", "Assilah", "Azemmour", "Azilal",
    "Beni Mellal", "Ben Guerir", "Berkane", "Berrechid", "Boujdour", "Bouznika",
    "Casablanca", "Chefchaouen", "Chichaoua", "Dakhla",
    "El Hajeb", "El Jadida", "Errachidia", "Essaouira", "Fès",
    "Fquih Ben Salah", "Guelmim", "Guercif",
    "Ifrane", "Imzouren", "Inezgane", "Jerada", "Kénitra", "Ksar El Kebir", "Khémisset", "Khénifra", "Khouribga",
    "Laâyoune", "Larache",
    "Marrakech", "Martil", "Meknès", "Midar", "Midelt", "Mohammédia",
    "Nador",
    "Ouarzazate", "Ouezzane", "Oujda",
    "Rabat", "Rehamna",
    "Safi", "Salé", "Sefrou", "Settat", "Sidi Bennour", "Sidi Ifni", "Sidi Kacem", "Sidi Slimane", "Skhirat", "Souk El Arbaa",
    "Tamesna", "Tan-Tan", "Tanger", "Taounate", "Taourirt", "Tarfaya", "Taroudant", "Tata", "Taza", "Témara", "Tétouan", "Tiflet", "Tinghir", "Tiznit",
    "Youssoufia", "Zagora"
]
comptes_bancaires = [
    "courant",
    "d’épargne",
    "professionnel",
    "joint",
    "salaire",
    "étudiant"
]
merchant_category_codes = {
    # Alimentation & Restaurants 🍔
    "5411": "Épiceries et supermarchés",
    "5812": "Restaurants",
    "5813": "Bars et discothèques",
    "5814": "Fast-food",

    # Transport & Voyages ✈️
    "4111": "Services de transport en commun",
    "4511": "Compagnies aériennes",
    "4722": "Agences de voyage",
    "5541": "Stations-service",

    # Santé & Médical 🏥
    "8011": "Médecins",
    "8021": "Dentistes",
    "8062": "Hôpitaux",
    "8099": "Services médicaux divers",

    # Achats & E-commerce 🛒
    "5311": "Grands magasins",
    "5691": "Magasins de vêtements",
    "5732": "Magasins d'électronique",
    "5942": "Librairies",

    # Services financiers 💰
    "6011": "Distributeurs automatiques de billets (ATM)",
    "6051": "Cryptomonnaies",
    "6211": "Courtiers en bourse",
    "6300": "Assurances"
}

job_Title = [
    'Psychologue, conseil',
    'Enseignant en besoins éducatifs spéciaux',
    'Agent de conservation de la nature',
    'Avocat en brevets',
    'Psychothérapeute en danse',
    'Urbaniste en transport',
    'Arboriculteur',
    'Designer, multimédia',
    'Consultant en affaires publiques',
    'Pathologiste',
    'Formateur informatique',
    'Développeur de systèmes',
    'Ingénieur en géotechnique',
    'Analyste de systèmes',
    'Architecte naval',
    'Radiologue, diagnostic',
    'Chercheur en programmation, radiodiffusion/film/vidéo',
    'Ingénieur en énergie',
    'Organisateur d\'événements',
    'Chercheur opérationnel',
    'Chercheur en marketing',
    'Officier de probation',
    'Directeur de centre de loisirs',
    'Banquier d\'investissement d\'entreprise',
    'Ergothérapeute',
    'Responsable du centre d\'appels',
    'Policier',
    'Responsable d\'éducation, musée',
    'Physiothérapeute',
    'Ingénieur réseau',
    'Psychologue légiste',
    'Géochimiste',
    'Officier de formation et d\'éducation des forces armées',
    'Designer de meubles',
    'Opticien, délivrance',
    'Psychologue, criminel',
    'Bibliothécaire, public',
    'Artiste peintre',
    'Scientifique, recherche (mathématiques)',
    'Responsable de la recherche, syndicat',
    'Responsable du tourisme',
    'Responsable des ressources humaines',
    'Géomètre, minéraux',
    'Développeur d\'applications',
    'Monteur vidéo',
    'Conservateur',
    'Responsable de la recherche, parti politique',
    'Ingénieur en mines',
    'Responsable de l\'éducation, communauté',
    'Physicien médical',
    'Horticulteur de loisirs',
    'Ingénieur en électricité',
    'Opérateur caméra de télévision',
    'Conseiller en carrières, enseignement supérieur',
    'Ambulancier',
    'Commerçant',
    'Infirmière pédiatrique',
    'Agent des normes commerciales',
    'Ingénieur, ventes techniques',
    'Designer, bijoux',
    'Biochimiste clinique',
    'Ingénieur en électronique',
    'Ingénieur en eau',
    'Écrivain scientifique',
    'Monteur film/vidéo',
    'Avocat, Écosse',
    'Scientifique en développement produit/processus',
    'Chirurgien de l\'arbre',
    'Conseiller en informations sur les carrières',
    'Géologue, ingénierie',
    'Conseiller',
    'Commissionnaire en fret',
    'Responsable principal des impôts/inspecteur des impôts',
    'Ingénieur en radiodiffusion (opérations)',
    'Enseignant de l\'anglais comme langue seconde',
    'Économiste',
    'Psychothérapeute pour enfants',
    'Inspecteur/évaluateur des demandes',
    'Responsable du centre d\'information touristique',
    'Responsable des expositions, musée/galerie',
    'Responsable des lieux',
    'Ingénieur biomédical',
    'Scientifique en recherche (sciences physiques)',
    'Responsable des achats',
    'Éditeur, caractéristiques de magazine',
    'Géologue des opérations',
    'Interprète',
    'Géologue en ingénierie',
    'Consultant en agriculture',
    'Paramédical',
    'Conseiller financier',
    'Administrateur, éducation',
    'Psychologue de l\'éducation',
    'Trader financier',
    'Scientifique audiologique',
    'Scientifique, audiologique',
    'Administrateur, organisations caritatives/volontaires',
    'Responsable des services de santé',
    'Marchandiseur de détail',
    'Chercheur en télécommunications',
    'Physiologiste de l\'exercice',
    'Technicien comptable',
    'Designer de produits',
    'Responsable de la gestion des déchets',
    'Ingénieur minier',
    'Chirurgien',
    'Thérapeute, horticulture',
    'Consultant en environnement',
    'Présentateur de diffusion',
    'Producteur, radio',
    'Ingénieur, communications',
    'Inspecteur/Conservateur de bâtiments historiques',
    'Enseignant, anglais comme langue étrangère',
    'Ingénieur en matériaux',
    'Visiteur de santé',
    'Secrétaire médical',
    'Directeur de théâtre',
    'Brasseur technique',
    'Géomètre de terrain/geomatique',
    'Ingénieur structure',
    'Radiographe diagnostique',
    'Assistant de production télévision',
    'Représentant commercial médical',
    'Contrôleur de bâtiment',
    'Thérapeute, sport',
    'Ingénieur structure',
    'Géomètre commercial/résidentiel',
    'Administrateur de base de données',
    'Designer d\'exposition',
    'Responsable formation et développement',
    'Ingénieur mécanique',
    'Physicien médical',
    'Administrateur',
    'Logger de boue',
    'Responsable de la pêche',
    'Conservateur, musée/galerie',
    'Programmeur, multimédia',
    'Cytogénéticien',
    'Programmeur multimédia',
    'Psychologue en conseil',
    'Chiropodiste',
    'Enseignant, petite enfance/pré',
    'Cartographe',
    'Consultant en pensions',
    'Enseignant primaire',
    'Ingénieur en électronique',
    'Responsable des expositions de musée/galerie',
    'Courtier en aéronautique',
    'Ingénieur chimiste',
    'Exécutif en compte publicitaire',
    'Exécutif de planification des comptes publicitaires',
    'Avocat juridique agréé (Angleterre et Pays de Galles)',
    'Infirmier psychiatrique',
    'Enseignant secondaire',
    'Bibliothécaire, académique',
    'Embryologiste clinique',
    'Immunologiste',
    'Manager de plateau de télévision',
    'Contractant',
    'Physicien de santé',
    'Copie',
    'Libraire',
    'Terre',
    'Expert en perte agréé',
    'Psychologue du travail',
    'Responsable des installations',
    'Conférencier d\'enseignement supérieur',
    'Archiviste',
    'Analyste d\'investissement',
    'Ingénieur en services de bâtiment',
    'Psychologue du sport et de l\'exercice',
    'Journaliste de presse',
    'Médecin, hôpital',
    'Phytothérapeute',
    'Pharmacologue',
    'Thérapeute horticole',
    'Hydrologue',
    'Travailleur en arts communautaires',
    'Responsable de maison publique',
    'Architecte',
    'Lexicographe',
    'Psychothérapeute pour enfants',
    'Enseignant, école secondaire',
    'Toxicologue',
    'Horticulteur commercial',
    'Podologue',
    'Géomètre de bâtiment',
    'Technologue architectural',
    'Éditeur, film/vidéo',
    'Chercheur social',
    'Géologue de site',
    'Designer, céramique/poterie',
    'Infirmier en santé mentale',
    'Coordinateur de bénévolat',
    'Directeur général de la technologie',
    'Opérateur caméra',
    'Rédacteur publicitaire',
    'Géomètre, mines',
    'Responsable de produit',
    'Infirmière, enfants',
    'Responsable du régime de retraite',
    'Archéologue',
    'Sous',
    'Designer, intérieur/spatial',
    'Trader de futures',
    'Directeur général',
    'Responsable des expositions éducatives au musée',
    'Géomètre en quantité',
    'Scientifique physiologique',
    'Ajusteur de pertes, agréé',
    'Pilote de ligne aérienne',
    'Assistant de production, radio',
    'Officier de l\'immigration',
    'Banquier de détail',
    'Conseiller en sécurité',
    'Enseignant, besoins éducatifs spéciaux',
    'Designer de bijoux',
    'Pharmacien communautaire',
    'Ingénieur en contrôle et instrumentation',
    'Faire',
    'Enseignant petite enfance',
    'Professionnel des ventes, informatique',
    'Scientifique marine',
    'Analyste de renseignement',
    'Associé de recherche clinique',
    'Administrateur, gouvernement local',
    'Avocat',
    'Ingénieur, contrôle et instrumentation',
    'Technologue textile/vêtements',
    'Travailleur de développement communautaire',
    'Thérapeute d\'art',
    'Exécutif des ventes',
    'Officier de soutien/logistique/administratif des forces armées',
    'Optométriste',
    'Souscripteur d\'assurance',
    'Responsable caritatif',
    'Civique rapide',
    'Acheteur de détail',
    'Rédacteur en caractéristiques de magazine',
    'Trader en actions',
    'Avocat en marques déposées',
    'Scientifique en recherche (sciences de la vie)',
    'Psychothérapeute',
    'Pharmacien communautaire',
    'Analyste de risques',
    'Ingénieur de maintenance'
]
transfer_type=['TPE', 'Desktop', 'Phone', 'DAB'] #DAB is ATM ( mean transation from GAP-Bank Agent)
